"""empty message

Revision ID: 48ddb8d12aad
Revises: 
Create Date: 2026-08-05 20:13:27.894181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ddb8d12aad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hashed', sa.String(length=255), nullable=False),
    sa.Column('correct_singleplayer_answers', sa.Integer(), nullable=True),
    sa.Column('incorrect_singleplayer_answers', sa.Integer(), nullable=True),
    sa.Column('multiplayer_game_wins', sa.Integer(), nullable=True),
    sa.Column('multiplayer_game_losses', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
